//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetMatch.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetMatch.Web.Resources.Pets", typeof(Pets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet &quot;{0}&quot; already exists..
        /// </summary>
        internal static string Pet_DuplicatedName {
            get {
                return ResourceManager.GetString("Pet_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by property must be set..
        /// </summary>
        internal static string Pet_EmptyCreatedBy {
            get {
                return ResourceManager.GetString("Pet_EmptyCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by property must be set..
        /// </summary>
        internal static string Pet_EmptyLastUpdatedBy {
            get {
                return ResourceManager.GetString("Pet_EmptyLastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is null or empty..
        /// </summary>
        internal static string Pet_EmptyName {
            get {
                return ResourceManager.GetString("Pet_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string Pet_MaxCreatedByLength {
            get {
                return ResourceManager.GetString("Pet_MaxCreatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for last updated by is 256 characters..
        /// </summary>
        internal static string Pet_MaxLastUpdatedByLength {
            get {
                return ResourceManager.GetString("Pet_MaxLastUpdatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for name is 100 characters..
        /// </summary>
        internal static string Pet_MaxNameLength {
            get {
                return ResourceManager.GetString("Pet_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet breed &quot;{0}&quot; already exists..
        /// </summary>
        internal static string PetBreed_DuplicatedName {
            get {
                return ResourceManager.GetString("PetBreed_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by property must be set..
        /// </summary>
        internal static string PetBreed_EmptyCreatedBy {
            get {
                return ResourceManager.GetString("PetBreed_EmptyCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by property must be set..
        /// </summary>
        internal static string PetBreed_EmptyLastUpdatedBy {
            get {
                return ResourceManager.GetString("PetBreed_EmptyLastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is null or empty..
        /// </summary>
        internal static string PetBreed_EmptyName {
            get {
                return ResourceManager.GetString("PetBreed_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string PetBreed_MaxCreatedByLength {
            get {
                return ResourceManager.GetString("PetBreed_MaxCreatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for last updated by is 256 characters..
        /// </summary>
        internal static string PetBreed_MaxLastUpdatedByLength {
            get {
                return ResourceManager.GetString("PetBreed_MaxLastUpdatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for name is 100 characters..
        /// </summary>
        internal static string PetBreed_MaxNameLength {
            get {
                return ResourceManager.GetString("PetBreed_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet type &quot;{0}&quot; already exists..
        /// </summary>
        internal static string PetType_DuplicatedName {
            get {
                return ResourceManager.GetString("PetType_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by property must be set..
        /// </summary>
        internal static string PetType_EmptyCreatedBy {
            get {
                return ResourceManager.GetString("PetType_EmptyCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated by property must be set..
        /// </summary>
        internal static string PetType_EmptyLastUpdatedBy {
            get {
                return ResourceManager.GetString("PetType_EmptyLastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is null or empty..
        /// </summary>
        internal static string PetType_EmptyName {
            get {
                return ResourceManager.GetString("PetType_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for created by is 256 characters..
        /// </summary>
        internal static string PetType_MaxCreatedByLength {
            get {
                return ResourceManager.GetString("PetType_MaxCreatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for last updated by is 256 characters..
        /// </summary>
        internal static string PetType_MaxLastUpdatedByLength {
            get {
                return ResourceManager.GetString("PetType_MaxLastUpdatedByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length for name is 100 characters..
        /// </summary>
        internal static string PetType_MaxNameLength {
            get {
                return ResourceManager.GetString("PetType_MaxNameLength", resourceCulture);
            }
        }
    }
}
